[project]
name = "cli-agent"
version = "0.1.0"
description = "CLI Agent's agent core"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "langchain-core>=0.3.78",
    "langchain-openai>=0.3.35",
    "python-dotenv>=1.1.1",
]
